#runtime: python37
#entrypoint: gunicorn -b :80 salud.wsgi
#
#handlers:
## This configures Google App Engine to serve the files in the app's static
## directory.
#- url: /static
#  static_dir: static_files/
#
## This handler routes all requests not caught above to your main app. It is
## required when static routes are defined, but can be omitted (along with
## the entire handlers section) when there are no static files defined.
#- url: .*
#  secure: always
#  redirect_http_response_code: 301
#  script: salud.wsgi.application


# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT salud.wsgi

beta_settings:
    cloud_sql_instances: salud-ab:us-east1:s5lud5b

runtime_config:
  python_version: 3
# [END runtime]
