# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170716_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='detalle',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='detalle',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
