# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField()),
                ('fecha_hora_mensaje_leido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alertas recibidas',
                'verbose_name_plural': 'Alertas recibidas',
                'ordering': ('fecha_hora_mensaje_leido',),
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('usuario', models.CharField(max_length=80)),
                ('fecha_hora_mensaje', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ('fecha_hora_mensaje',),
            },
        ),
        migrations.AddField(
            model_name='alertarecibida',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Alertas'),
        ),
    ]
