# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmedicas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_Cita',
        ),
        migrations.AlterModelOptions(
            name='citas',
            options={'ordering': ('id',), 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='usuarios.Paciente'),
        ),
    ]
