# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0002_auto_20171127_0411'),
        ('usuarios', '0003_auto_20171127_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('cita_para', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('nota_para_la_cita', models.TextField()),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('P', 'En proceso'), ('T', 'Terminada')], default='A', max_length=1)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.Habitacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ('cita_para',),
            },
        ),
        migrations.CreateModel(
            name='Consulta_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('detalles', models.TextField()),
                ('receta', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasmedicas.Citas')),
            ],
            options={
                'verbose_name': 'Consulta Medica',
                'verbose_name_plural': 'Consultas Medicas',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Tipo de cita',
                'verbose_name_plural': 'Tipos de citas',
                'ordering': ('nombre',),
            },
        ),
    ]
