# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='en_pasillo',
        ),
        migrations.RemoveField(
            model_name='pasillo',
            name='en_la_sala',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='en_lugar',
        ),
        migrations.AlterField(
            model_name='citas',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.Habitacion'),
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Pasillo',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
