# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20171127_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='consulta_medica',
            name='cita',
        ),
        migrations.DeleteModel(
            name='Tipo_Cita',
        ),
        migrations.DeleteModel(
            name='Citas',
        ),
        migrations.DeleteModel(
            name='Consulta_Medica',
        ),
    ]
