# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20171127_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image_de_perfil',
            field=models.ImageField(default=django.utils.timezone.now, max_length=254, upload_to='photos'),
            preserve_default=False,
        ),
    ]
