# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170716_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='Medico',
            new_name='medico',
        ),
    ]
