# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('entidad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('cedula', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Cedula de la persona')),
                ('first_name', models.CharField(db_index=True, max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, max_length=80, verbose_name='Apellido')),
                ('es_medico', models.BooleanField(default=False)),
                ('es_paciente', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image_de_perfil', models.ImageField(max_length=254, upload_to='photos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ('especialidad',),
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TextField()),
                ('telefono', models.TextField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('fecha_registrado', models.DateTimeField(auto_now_add=True)),
                ('en_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.Sucursal')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ('usuario',),
            },
        ),
        migrations.CreateModel(
            name='MedicoEnTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('en_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.Habitacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Medico')),
            ],
            options={
                'verbose_name': 'Medico en turno',
                'verbose_name_plural': 'Medicos en turno',
                'ordering': ('medico',),
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=800)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('O-', 'O negativo'), ('O+', 'O positivo'), ('A-', 'A negativo'), ('A+', 'A positivo'), ('B-', 'B negativo'), ('B+', 'B positivo'), ('AB-', 'AB negativo'), ('AB+', 'AB positivo')], max_length=3)),
                ('peso', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('reacciones_alergicas', models.TextField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('ocupacion', models.TextField(blank=True, null=True)),
                ('nota_medica', models.TextField(blank=True, null=True)),
                ('seguro_medico', models.CharField(blank=True, max_length=200, null=True)),
                ('en_lugar', models.ManyToManyField(to='entidad.Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('usuario',),
            },
        ),
    ]
