# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoenturno',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('V', 'Vencido')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
