# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_medicoenturno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicoenturno',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('V', 'Vencido')], default='A', max_length=1),
        ),
    ]
